package com.example.mysmartlist.Utils;

/**
 * Created by E610 on 2/21/2018.
 */

public class Constants {


    public static final  String danubeBasicUrl="https://danube.sa";
    public static final  String localHostIp="http://192.168.1.8";
    public static final  String BasicUrl = "https://smartlist.frb.io/api/";
    public static final  String BasicUrlImg = "https://smartlist.frb.io/";
    public static final  String accessToken="Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjQ1MDRlZWJiMTg4ODQ0YTM1MzUwMjhlYTE5MTFmMGI1OTUyN2U3NmM4OWJhMzRiNTZmN2Q5Y2JlYzAwNjI4MjgyNGYzMTUyNmJjMzIxYWMzIn0.eyJhdWQiOiIyIiwianRpIjoiNDUwNGVlYmIxODg4NDRhMzUzNTAyOGVhMTkxMWYwYjU5NTI3ZTc2Yzg5YmEzNGI1NmY3ZDljYmVjMDA2MjgyODI0ZjMxNTI2YmMzMjFhYzMiLCJpYXQiOjE1MjA3OTA3NDgsIm5iZiI6MTUyMDc5MDc0OCwiZXhwIjoxNTUyMzI2NzQ4LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.EnUurWBVeNMrDCeE1q2fWxD4gXfJBkgOJrhAV-Ui91YHiJJKSR9ZlipbX9vvEECY_bbMZDwZgEYIOV3tLGo6Z0W4XVT2V5uMQ2VAw_u9xoBALmzz1zQ6BNZ2WbGx_oXWmHZoyLC2CYQssw1WtHJiVrrIiUlkNhMuKlr1_8xFVY1UadU9nIYahw_qZuhDmYpk186UyJZ7sZcojze2rUnBhxFj3bypfEUuW_MZanxD7oBMGwpFLc5RjLURzGgaPebjoAtf_VBadgVJRBB3WPYfzrU4gOdT4_yoYjRJWU76XQf7pOXYBy5yzcXn_3u0MWEgH_UuHvyB_TT2nRAoOnkFPVd48RzVSvLKRPkagbnR4Q6WZwkghC83x9Hyllih2o1C0aGYVnYh-pjUjeFUdEng1RjWR3qbQRpVUwMValm964mkD1Gq5cOUl6L3rCIXm6oKp4VQMlJSS8yXlYqwyuPUJjnegTKCXYgBqa12MCyH1oUTf2AD3P0z6BytHCXxlfTjVrqxwfp4JoDRUHEVAAIcfovrrkZjRKZH_rM5i8d7RtgnlgtOeOtwdNo6SGV0DaaS2j3qKYfkfNLtRjX_OlzZk9kRgIITxYwPFsYJlQ4KoDdJpQgpXj_sl3kFhuIMXsl4CM58yOKfHmxNHGFUl2TcJnXQh0tuCYaHZ1utW18AvsY";
}
